#!/bin/sh
# skerry-init — run on every docker compose up -d
# Reads .env (user config), merges into .env.ops (runtime env for compose).
# Generated secrets persist across restarts. User edits to .env are picked up.
set -e

ENV_USER=".env"
ENV_OPS=".env.ops"
SYNAPSE_CONFIG_DIR="docker/synapse"
SYNAPSE_SIGNING_KEY="${SYNAPSE_CONFIG_DIR}/hub-localhost.signing.key"

# ---------- validate ----------
if [ ! -f "$ENV_USER" ]; then
  echo "ERROR: $ENV_USER not found. This file is included in the deploy kit."
  exit 1
fi

BASE_DOMAIN=$(grep -E '^BASE_DOMAIN=' "$ENV_USER" | sed 's/^BASE_DOMAIN=//' | tr -d '"'"'"' || true)
if [ -z "$BASE_DOMAIN" ]; then
  echo "ERROR: BASE_DOMAIN is not set in $ENV_USER."
  echo "  Edit $ENV_USER and set BASE_DOMAIN to your domain (e.g. BASE_DOMAIN=skerry.chat)"
  exit 1
fi

# ---------- load existing .env.ops if present ----------
if [ -f "$ENV_OPS" ]; then
  # shellcheck disable=SC1090
  . "$ENV_OPS"
fi

# ---------- generate secrets (only if not already set) ----------
gen_secret() {
  openssl rand -hex 32
}

POSTGRES_USER="${POSTGRES_USER:-skerry}"
POSTGRES_DB="${POSTGRES_DB:-skerry}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-$(gen_secret)}"
SESSION_SECRET="${SESSION_SECRET:-$(gen_secret)}"
SYNAPSE_AS_TOKEN="${SYNAPSE_AS_TOKEN:-$(gen_secret)}"
SYNAPSE_HS_TOKEN="${SYNAPSE_HS_TOKEN:-$(gen_secret)}"

# ---------- pull user overrides from .env ----------
load_user_value() {
  local key=$1
  grep -E "^${key}=" "$ENV_USER" 2>/dev/null | tail -1 | sed "s/^${key}=//" | tr -d '"'"'"' || true
}

for key in \
  BASE_DOMAIN \
  EMAIL \
  DISCORD_CLIENT_ID DISCORD_CLIENT_SECRET DISCORD_BOT_TOKEN \
  GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET \
  TWITCH_CLIENT_ID TWITCH_CLIENT_SECRET \
  SKERRY_VERSION \
  ; do
  val=$(load_user_value "$key")
  if [ -n "$val" ]; then
    eval "$key=\$val"
  fi
done

# ---------- write .env.ops ----------
cat > "$ENV_OPS" << EOF
# Generated by skerry-init — do not edit manually.
# Edit .env instead; changes are merged on next start.

BASE_DOMAIN=$BASE_DOMAIN
POSTGRES_USER=$POSTGRES_USER
POSTGRES_DB=$POSTGRES_DB
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
SESSION_SECRET=$SESSION_SECRET
SYNAPSE_AS_TOKEN=$SYNAPSE_AS_TOKEN
SYNAPSE_HS_TOKEN=$SYNAPSE_HS_TOKEN
SYNAPSE_AS_REGISTRATION_PATH=/app/docker/synapse/skerry-appservice.yaml

DISCORD_CLIENT_ID=$DISCORD_CLIENT_ID
DISCORD_CLIENT_SECRET=$DISCORD_CLIENT_SECRET
DISCORD_BOT_TOKEN=$DISCORD_BOT_TOKEN

# Control-plane uses separate names for OIDC vs bridge (both from same app)
OIDC_DISCORD_CLIENT_ID=$DISCORD_CLIENT_ID
OIDC_DISCORD_CLIENT_SECRET=$DISCORD_CLIENT_SECRET
DISCORD_BRIDGE_CLIENT_ID=$DISCORD_CLIENT_ID
DISCORD_BRIDGE_CLIENT_SECRET=$DISCORD_CLIENT_SECRET
DISCORD_BRIDGE_BOT_TOKEN=$DISCORD_BOT_TOKEN

GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
OIDC_GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
OIDC_GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
TWITCH_CLIENT_ID=$TWITCH_CLIENT_ID
TWITCH_CLIENT_SECRET=$TWITCH_CLIENT_SECRET
OIDC_TWITCH_CLIENT_ID=$TWITCH_CLIENT_ID
OIDC_TWITCH_CLIENT_SECRET=$TWITCH_CLIENT_SECRET
EMAIL=$EMAIL

SKERRY_VERSION=${SKERRY_VERSION:-v0.1.0-alpha}

# Internal defaults
LIVEKIT_API_KEY=devkey
LIVEKIT_API_SECRET=secret
SYNAPSE_BASE_URL=http://synapse:8008
SYNAPSE_SERVER_NAME=hub-localhost
LIVEKIT_URL=ws://livekit:7880
EOF

# ---------- generate Synapse signing key ----------
if [ ! -f "$SYNAPSE_SIGNING_KEY" ]; then
  echo "Generating Synapse signing key..."
  openssl genpkey -algorithm ED25519 -out "$SYNAPSE_SIGNING_KEY"
fi

echo "skerry-init: .env.ops is ready"
