#!/bin/sh
# start.sh — start Skerry services
#   ./scripts/start.sh          first run: init secrets, start everything
#   ./scripts/start.sh          subsequent runs: merge .env changes, start (no pull)
#
#   For upgrades:  ./scripts/upgrade.sh
#   To stop:       ./scripts/stop.sh
set -e

SCRIPTS_DIR="$(cd "$(dirname "$0")" && pwd)"
SKERRY_DIR="$(cd "$SCRIPTS_DIR/.." && pwd)"
cd "$SKERRY_DIR"

ENV_USER=".env"
ENV_OPS=".env.ops"
SYNAPSE_CONFIG_DIR="docker/synapse"
SYNAPSE_SIGNING_KEY="${SYNAPSE_CONFIG_DIR}/hub-localhost.signing.key"
SYNAPSE_HOMESERVER="${SYNAPSE_CONFIG_DIR}/homeserver.yaml"

# ---------- pre-flight validation ----------
if [ ! -f "$ENV_USER" ]; then
  echo "ERROR: $ENV_USER not found. This file is included in the deploy kit."
  exit 1
fi

# shellcheck disable=SC1090
. "./$ENV_USER"

if [ -z "$BASE_DOMAIN" ] || [ "$BASE_DOMAIN" = "localhost" ]; then
  echo "NOTE: BASE_DOMAIN is not set or is 'localhost'."
  echo "  Edit $ENV_USER and set BASE_DOMAIN to your domain."
  echo "  Continuing with localhost — services will be reachable at http://localhost"
fi

# ---------- helpers ----------
gen_secret() {
  dd if=/dev/urandom bs=32 count=1 2>/dev/null | hexdump -v -e '/1 "%02x"'
}

load_user_value() {
  local key=$1
  grep -E "^${key}=" "$ENV_USER" 2>/dev/null | tail -1 | sed -e "s/^${key}=//" -e "s/^[\"']//" -e "s/[\"']$//" || true
}

# ---------- load existing or generate fresh ----------
OPS_EXISTED=false
if [ -f "$ENV_OPS" ]; then
  OPS_EXISTED=true
  # shellcheck disable=SC1090
  . "./$ENV_OPS"
else
  echo "First run: generating secrets..."
fi

# --- secrets (generate only if not already set from .env.ops or .env) ---
POSTGRES_USER="${POSTGRES_USER:-skerry}"
POSTGRES_DB="${POSTGRES_DB:-skerry}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-$(gen_secret)}"
SESSION_SECRET="${SESSION_SECRET:-$(gen_secret)}"
SYNAPSE_AS_TOKEN="${SYNAPSE_AS_TOKEN:-$(gen_secret)}"
SYNAPSE_HS_TOKEN="${SYNAPSE_HS_TOKEN:-$(gen_secret)}"
LIVEKIT_API_KEY="${LIVEKIT_API_KEY:-$(gen_secret)}"
LIVEKIT_API_SECRET="${LIVEKIT_API_SECRET:-$(gen_secret)}"
SETUP_BOOTSTRAP_TOKEN="${SETUP_BOOTSTRAP_TOKEN:-$(gen_secret)}"

# --- internal defaults ---
SYNAPSE_BASE_URL="${SYNAPSE_BASE_URL:-http://synapse:8008}"
SYNAPSE_SERVER_NAME="${SYNAPSE_SERVER_NAME:-hub-localhost}"
LIVEKIT_URL="${LIVEKIT_URL:-ws://livekit:7880}"
SKERRY_VERSION="${SKERRY_VERSION:-latest}"

# --- pull user overrides from .env (runs every time, picks up edits) ---
for key in \
  BASE_DOMAIN \
  CLOUDFLARE_TUNNEL_TOKEN \
  COMPOSE_PROFILES \
  EMAIL \
  DISCORD_CLIENT_ID DISCORD_CLIENT_SECRET DISCORD_BOT_TOKEN \
  GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET \
  TWITCH_CLIENT_ID TWITCH_CLIENT_SECRET \
  LIVEKIT_API_KEY LIVEKIT_API_SECRET \
  SETUP_BOOTSTRAP_TOKEN \
  SKERRY_VERSION \
  SYNAPSE_BASE_URL SYNAPSE_SERVER_NAME LIVEKIT_URL \
  DATABASE_URL \
  ; do
  val=$(load_user_value "$key")
  if [ -n "$val" ]; then
    eval "$key=\$val"
  fi
done

# --- write .env.ops (idempotent — runs every time to pick up .env changes) ---
cat > "$ENV_OPS" << EOF
# Generated by start.sh — do not edit manually.
# Edit .env instead; changes are picked up on next start.

BASE_DOMAIN=$BASE_DOMAIN
POSTGRES_USER=$POSTGRES_USER
POSTGRES_DB=$POSTGRES_DB
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
PGHOST=postgres
PGUSER=$POSTGRES_USER
PGPASSWORD=$POSTGRES_PASSWORD
PGDATABASE=$POSTGRES_DB
DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB
SESSION_SECRET=$SESSION_SECRET
SYNAPSE_AS_TOKEN=$SYNAPSE_AS_TOKEN
SYNAPSE_HS_TOKEN=$SYNAPSE_HS_TOKEN
SYNAPSE_AS_REGISTRATION_PATH=/app/docker/synapse/skerry-appservice.yaml

CLOUDFLARE_TUNNEL_TOKEN=$CLOUDFLARE_TUNNEL_TOKEN
COMPOSE_PROFILES=$COMPOSE_PROFILES

DISCORD_CLIENT_ID=$DISCORD_CLIENT_ID
DISCORD_CLIENT_SECRET=$DISCORD_CLIENT_SECRET
DISCORD_BOT_TOKEN=$DISCORD_BOT_TOKEN

OIDC_DISCORD_CLIENT_ID=$DISCORD_CLIENT_ID
OIDC_DISCORD_CLIENT_SECRET=$DISCORD_CLIENT_SECRET
DISCORD_BRIDGE_CLIENT_ID=$DISCORD_CLIENT_ID
DISCORD_BRIDGE_CLIENT_SECRET=$DISCORD_CLIENT_SECRET
DISCORD_BRIDGE_BOT_TOKEN=$DISCORD_BOT_TOKEN

GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
OIDC_GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
OIDC_GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
TWITCH_CLIENT_ID=$TWITCH_CLIENT_ID
TWITCH_CLIENT_SECRET=$TWITCH_CLIENT_SECRET
OIDC_TWITCH_CLIENT_ID=$TWITCH_CLIENT_ID
OIDC_TWITCH_CLIENT_SECRET=$TWITCH_CLIENT_SECRET
EMAIL=${EMAIL:-admin@localhost}

SKERRY_VERSION=${SKERRY_VERSION:-latest}

LIVEKIT_API_KEY=$LIVEKIT_API_KEY
LIVEKIT_API_SECRET=$LIVEKIT_API_SECRET
SETUP_BOOTSTRAP_TOKEN=$SETUP_BOOTSTRAP_TOKEN
SYNAPSE_BASE_URL=$SYNAPSE_BASE_URL
SYNAPSE_SERVER_NAME=$SYNAPSE_SERVER_NAME
LIVEKIT_URL=$LIVEKIT_URL
EOF

# --- Synapse prep (one-time: signing key, homeserver password) ---
mkdir -p "${SYNAPSE_CONFIG_DIR}/media_store"
chmod 777 "${SYNAPSE_CONFIG_DIR}/media_store" 2>/dev/null || true

if [ ! -f "$SYNAPSE_SIGNING_KEY" ]; then
  echo "Generating Synapse signing key..."
  KEY_ID="a_$(dd if=/dev/urandom bs=3 count=1 2>/dev/null | hexdump -v -e '/1 "%02x"')"
  SEED=$(dd if=/dev/urandom bs=43 count=1 2>/dev/null | base64 | tr -d '\n' | head -c 43)
  echo "ed25519 ${KEY_ID} ${SEED}" > "$SYNAPSE_SIGNING_KEY"
  chmod 644 "$SYNAPSE_SIGNING_KEY"
fi

if [ -f "$SYNAPSE_HOMESERVER" ]; then
  sed -i "s/__POSTGRES_PASSWORD__/${POSTGRES_PASSWORD}/g" "$SYNAPSE_HOMESERVER"
fi

if [ "$OPS_EXISTED" = false ]; then
  echo ""
  echo "============================================"
  echo "  Bootstrap token: $SETUP_BOOTSTRAP_TOKEN"
  echo ""
  echo "  Visit http://${BASE_DOMAIN}, log in, and enter"
  echo "  this token when prompted during initial setup."
  echo "============================================"
  echo ""
fi

# ---------- export config and regenerate appservice YAML ----------
set -a
# shellcheck disable=SC1090
. "./$ENV_OPS"
set +a

# Runs every start so .env changes and upgrades pick up correct tokens.
cat > "${SYNAPSE_CONFIG_DIR}/skerry-appservice.yaml" << EOF
id: Skerry
url: http://control-plane:4000
as_token: ${SYNAPSE_AS_TOKEN}
hs_token: ${SYNAPSE_HS_TOKEN}
sender_localpart: skerry-bot
namespaces:
  users:
    - exclusive: false
      regex: "@.*"
  rooms: []
  aliases: []
EOF

# ---------- start or init-only ----------
if [ "${1:-}" = "--init-only" ]; then
  echo "Init complete — .env.ops is ready. Skipping service start (--init-only)."
  exit 0
fi

echo "Starting services..."
if ! docker compose up -d; then
  echo ""
  echo "ERROR: docker compose up failed. Capturing logs from exited containers..."
  for cid in $(docker compose ps --status exited -q 2>/dev/null); do
    echo "=== $cid logs ==="
    docker logs "$cid" 2>&1 | tail -80
  done
  exit 1
fi

echo ""
echo "Skerry is starting. Check status with: docker compose ps"
echo "Web UI: http://${BASE_DOMAIN}"
