#!/bin/sh
# upgrade.sh — download latest release kit, merge .env changes, pull images, restart
#   Pinned:   set SKERRY_VERSION=v0.5.3-alpha in .env
#   Rolling:  leave unset (defaults to latest release)
set -e

SCRIPTS_DIR="$(cd "$(dirname "$0")" && pwd)"
SKERRY_DIR="$(cd "$SCRIPTS_DIR/.." && pwd)"
cd "$SKERRY_DIR"

# ---------- resolve version ----------
# Load SKERRY_VERSION from .env.ops (generated by start.sh from .env)
if [ -f ".env.ops" ]; then
  # shellcheck disable=SC1090
  . "./.env.ops"
fi

VERSION="${SKERRY_VERSION:-latest}"
if [ "$VERSION" = "latest" ]; then
  echo "Resolving latest release..."
  VERSION=$(wget -qO- https://api.github.com/repos/SecareLupus/Skerry/releases/latest 2>/dev/null | grep -o '"tag_name": *"[^"]*"' | head -1 | sed 's/.*"\([^"]*\)".*/\1/')
  if [ -z "$VERSION" ]; then
    echo "ERROR: Could not determine latest release. Is the server reachable?"
    exit 1
  fi
fi

echo "Upgrading to ${VERSION}..."

# ---------- download and extract release tarball ----------
TARBALL="skerry-deploy-${VERSION}.tar.gz"
URL="https://github.com/SecareLupus/Skerry/releases/download/${VERSION}/${TARBALL}"
TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

echo "Downloading ${TARBALL}..."
wget -q -O "${TMPDIR}/${TARBALL}" "$URL" || {
  echo "ERROR: Failed to download ${URL}"
  exit 1
}

echo "Extracting..."
tar -xzf "${TMPDIR}/${TARBALL}" -C "$TMPDIR"

# ---------- sync files (preserving .env and .env.ops) ----------
# The tarball contains a 'skerry/' directory.
# Copy everything except .env and .env.ops so user config is never overwritten.
SRC="${TMPDIR}/skerry"
if [ ! -d "$SRC" ]; then
  echo "ERROR: Tarball does not contain expected skerry/ directory"
  exit 1
fi

echo "Syncing release files..."
for item in "$SRC"/* "$SRC"/.[!.]* "$SRC"/..?*; do
  [ -e "$item" ] || continue
  base=$(basename "$item")
  case "$base" in
    .env|.env.ops) continue ;;    # never overwrite user config
    *) cp -r "$item" "$SKERRY_DIR/" ;;
  esac
done

# ---------- merge .env → .env.ops, regen appservice YAML ----------
"$SCRIPTS_DIR/start.sh" --init-only

# ---------- pull and restart ----------
. "./.env.ops"
export SKERRY_VERSION
export COMPOSE_PROFILES
export LIVEKIT_KEYS="${LIVEKIT_API_KEY}: ${LIVEKIT_API_SECRET}"

echo "Pulling images (${SKERRY_VERSION})..."
docker compose pull

echo "Restarting changed services..."
docker compose up -d

echo ""
echo "Upgrade to ${VERSION} complete. Check status with: docker compose ps"
